name: AntiDropScattering
version: '1.0-SNAPSHOT'
main: me.deaglewolf.antidropscattering.AntiDropScattering
api-version: '1.21'

commands:
  ads:
    description: "AntiDropScattering management command."

permissions:
  ads.admin:
    default: op
