name: AntiDropScattering
version: '1.2'
main: me.deaglewolf.antidropscattering.AntiDropScattering
api-version: '1.21'
folia-supported: true
commands:
  ads:
    description: "AntiDropScattering management command."

permissions:
  ads.admin:
    default: op
